config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :eventos
  resources :salas
  resources :locals
  resources :productos
  resources :tipo_productos
    devise_for :users
    authenticated :user do
        root 'welcome#index'
    end

    unauthenticated :user do
        devise_scope :user do
        root 'welcome#unregistered', as: :unregistered_root
        end
    end
end

app/models/reserva.rb
class Reserva < ApplicationRecord
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:co_reserva, :co_sala, :co_cliente, :fe_reserva, :tx_descripcion)
    end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.haml
= form_for @reserva do |f|
  - if @reserva.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reserva.errors.count, "error")} prohibited this reserva from being saved:"
      %ul
        - @reserva.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :co_reserva
    = f.number_field :co_reserva
  .field
    = f.label :co_sala
    = f.number_field :co_sala
  .field
    = f.label :co_cliente
    = f.number_field :co_cliente
  .field
    = f.label :fe_reserva
    = f.date_select :fe_reserva
  .field
    = f.label :tx_descripcion
    = f.text_area :tx_descripcion
  .actions
    = f.submit 'Save'

app/views/reservas/edit.html.haml
%h1 Editing reserva

= render 'form'

= link_to 'Show', @reserva
\|
= link_to 'Back', reservas_path

app/views/reservas/index.html.haml
%h1 Listing reservas

%table
  %thead
    %tr
      %th Co reserva
      %th Co sala
      %th Co cliente
      %th Fe reserva
      %th Tx descripcion
      %th
      %th
      %th

  %tbody
    - @reservas.each do |reserva|
      %tr
        %td= reserva.co_reserva
        %td= reserva.co_sala
        %td= reserva.co_cliente
        %td= reserva.fe_reserva
        %td= reserva.tx_descripcion
        %td= link_to 'Show', reserva
        %td= link_to 'Edit', edit_reserva_path(reserva)
        %td= link_to 'Destroy', reserva, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Reserva', new_reserva_path

app/views/reservas/new.html.haml
%h1 New reserva

= render 'form'

= link_to 'Back', reservas_path

app/views/reservas/show.html.haml
%p#notice= notice

%p
  %b Co reserva:
  = @reserva.co_reserva
%p
  %b Co sala:
  = @reserva.co_sala
%p
  %b Co cliente:
  = @reserva.co_cliente
%p
  %b Fe reserva:
  = @reserva.fe_reserva
%p
  %b Tx descripcion:
  = @reserva.tx_descripcion

= link_to 'Edit', edit_reserva_path(@reserva)
\|
= link_to 'Back', reservas_path