config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :eventos
  resources :salas
  resources :locals
  resources :productos
  resources :tipo_productos
    devise_for :users
    authenticated :user do
        root 'welcome#index'
    end

    unauthenticated :user do
        devise_scope :user do
        root 'welcome#unregistered', as: :unregistered_root
        end
    end
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:co_evento, :co_local, :f_evento, :capacidad, :descripcion)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.haml
= form_for @evento do |f|
  - if @evento.errors.any?
    #error_explanation
      %h2= "#{pluralize(@evento.errors.count, "error")} prohibited this evento from being saved:"
      %ul
        - @evento.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :co_evento
    = f.number_field :co_evento
  .field
    = f.label :co_local
    = f.number_field :co_local
  .field
    = f.label :f_evento
    = f.date_select :f_evento
  .field
    = f.label :capacidad
    = f.number_field :capacidad
  .field
    = f.label :descripcion
    = f.text_area :descripcion
  .actions
    = f.submit 'Save'

app/views/eventos/edit.html.haml
%h1 Editing evento

= render 'form'

= link_to 'Show', @evento
\|
= link_to 'Back', eventos_path

app/views/eventos/index.html.haml
%h1 Listing eventos

%table
  %thead
    %tr
      %th Co evento
      %th Co local
      %th F evento
      %th Capacidad
      %th Descripcion
      %th
      %th
      %th

  %tbody
    - @eventos.each do |evento|
      %tr
        %td= evento.co_evento
        %td= evento.co_local
        %td= evento.f_evento
        %td= evento.capacidad
        %td= evento.descripcion
        %td= link_to 'Show', evento
        %td= link_to 'Edit', edit_evento_path(evento)
        %td= link_to 'Destroy', evento, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Evento', new_evento_path

app/views/eventos/new.html.haml
%h1 New evento

= render 'form'

= link_to 'Back', eventos_path

app/views/eventos/show.html.haml
%p#notice= notice

%p
  %b Co evento:
  = @evento.co_evento
%p
  %b Co local:
  = @evento.co_local
%p
  %b F evento:
  = @evento.f_evento
%p
  %b Capacidad:
  = @evento.capacidad
%p
  %b Descripcion:
  = @evento.descripcion

= link_to 'Edit', edit_evento_path(@evento)
\|
= link_to 'Back', eventos_path