config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :eventos
  resources :salas
  resources :locals
  resources :productos
  resources :tipo_productos
    devise_for :users
    authenticated :user do
        root 'welcome#index'
    end

    unauthenticated :user do
        devise_scope :user do
        root 'welcome#unregistered', as: :unregistered_root
        end
    end
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:co_producto, :co_tipoproducto, :no_producto, :ss_precio, :qt_stock)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.haml
= form_for @producto do |f|
  - if @producto.errors.any?
    #error_explanation
      %h2= "#{pluralize(@producto.errors.count, "error")} prohibited this producto from being saved:"
      %ul
        - @producto.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :co_producto
    = f.number_field :co_producto
  .field
    = f.label :co_tipoproducto
    = f.number_field :co_tipoproducto
  .field
    = f.label :no_producto
    = f.text_field :no_producto
  .field
    = f.label :ss_precio
    = f.text_field :ss_precio
  .field
    = f.label :qt_stock
    = f.number_field :qt_stock
  .actions
    = f.submit 'Save'

app/views/productos/edit.html.haml
%h1 Editing producto

= render 'form'

= link_to 'Show', @producto
\|
= link_to 'Back', productos_path

app/views/productos/index.html.haml
%h1 Listing productos

%table
  %thead
    %tr
      %th Co producto
      %th Co tipoproducto
      %th No producto
      %th Ss precio
      %th Qt stock
      %th
      %th
      %th

  %tbody
    - @productos.each do |producto|
      %tr
        %td= producto.co_producto
        %td= producto.co_tipoproducto
        %td= producto.no_producto
        %td= producto.ss_precio
        %td= producto.qt_stock
        %td= link_to 'Show', producto
        %td= link_to 'Edit', edit_producto_path(producto)
        %td= link_to 'Destroy', producto, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Producto', new_producto_path

app/views/productos/new.html.haml
%h1 New producto

= render 'form'

= link_to 'Back', productos_path

app/views/productos/show.html.haml
%p#notice= notice

%p
  %b Co producto:
  = @producto.co_producto
%p
  %b Co tipoproducto:
  = @producto.co_tipoproducto
%p
  %b No producto:
  = @producto.no_producto
%p
  %b Ss precio:
  = @producto.ss_precio
%p
  %b Qt stock:
  = @producto.qt_stock

= link_to 'Edit', edit_producto_path(@producto)
\|
= link_to 'Back', productos_path