config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :eventos
  resources :salas
  resources :locals
  resources :productos
  resources :tipo_productos
    devise_for :users
    authenticated :user do
        root 'welcome#index'
    end

    unauthenticated :user do
        devise_scope :user do
        root 'welcome#unregistered', as: :unregistered_root
        end
    end
end

app/models/sala.rb
class Sala < ApplicationRecord
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]

  # GET /salas
  # GET /salas.json
  def index
    @salas = Sala.all
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
  end

  # GET /salas/new
  def new
    @sala = Sala.new
  end

  # GET /salas/1/edit
  def edit
  end

  # POST /salas
  # POST /salas.json
  def create
    @sala = Sala.new(sala_params)

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render :show, status: :created, location: @sala }
      else
        format.html { render :new }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salas/1
  # PATCH/PUT /salas/1.json
  def update
    respond_to do |format|
      if @sala.update(sala_params)
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { render :show, status: :ok, location: @sala }
      else
        format.html { render :edit }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url, notice: 'Sala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sala_params
      params.require(:sala).permit(:co_sala, :co_local, :no_sala, :capacidad, :descripcion)
    end
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/salas/_form.html.haml
= form_for @sala do |f|
  - if @sala.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sala.errors.count, "error")} prohibited this sala from being saved:"
      %ul
        - @sala.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :co_sala
    = f.number_field :co_sala
  .field
    = f.label :co_local
    = f.number_field :co_local
  .field
    = f.label :no_sala
    = f.number_field :no_sala
  .field
    = f.label :capacidad
    = f.number_field :capacidad
  .field
    = f.label :descripcion
    = f.text_area :descripcion
  .actions
    = f.submit 'Save'

app/views/salas/edit.html.haml
%h1 Editing sala

= render 'form'

= link_to 'Show', @sala
\|
= link_to 'Back', salas_path

app/views/salas/index.html.haml
%h1 Listing salas

%table
  %thead
    %tr
      %th Co sala
      %th Co local
      %th No sala
      %th Capacidad
      %th Descripcion
      %th
      %th
      %th

  %tbody
    - @salas.each do |sala|
      %tr
        %td= sala.co_sala
        %td= sala.co_local
        %td= sala.no_sala
        %td= sala.capacidad
        %td= sala.descripcion
        %td= link_to 'Show', sala
        %td= link_to 'Edit', edit_sala_path(sala)
        %td= link_to 'Destroy', sala, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sala', new_sala_path

app/views/salas/new.html.haml
%h1 New sala

= render 'form'

= link_to 'Back', salas_path

app/views/salas/show.html.haml
%p#notice= notice

%p
  %b Co sala:
  = @sala.co_sala
%p
  %b Co local:
  = @sala.co_local
%p
  %b No sala:
  = @sala.no_sala
%p
  %b Capacidad:
  = @sala.capacidad
%p
  %b Descripcion:
  = @sala.descripcion

= link_to 'Edit', edit_sala_path(@sala)
\|
= link_to 'Back', salas_path